name: 'C++ CI'

on:
  push:
    branches:
      - main
      - master
      - feature/github_actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        run: |
          gh release create v${{ github.run_number }} \
            ./helloworld-0.0.${{ github.run_number }}-Linux.deb \
            --title "Release ${{ github.run_number }}" \
            --generate-release-notes || echo "Release already exists"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}